target 'KarteTrackerSample' do
  pod 'Firebase/Core'
  pod 'Firebase/Messaging'
  pod 'KarteTracker'
end

target 'NotificationService' do
  platform :ios, '10.0'
  pod 'KarteTrackerAppExtensions'
end
